FROM golang:1.23-alpine

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Download dependencies
RUN go mod tidy

# Build the API binary
RUN go build -o api api.go db.go

# Expose the API port
EXPOSE 3001

# Command to run the API
CMD ["./api"]
